<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1710_entercode</name>
   <tag></tag>
   <elementGuidId>f1e2a0ed-6fe5-4545-86c8-4713300d1314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#code</value>
   </webElementProperties>
</WebElementEntity>
