<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1740_7</name>
   <tag></tag>
   <elementGuidId>5e071d42-e7a0-45cd-bfdf-bed7aead3f00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M1740_BD_NONE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M1740_BD_NONE</value>
   </webElementProperties>
</WebElementEntity>
