<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1740_4</name>
   <tag></tag>
   <elementGuidId>44bc8b87-b6fd-4219-8c56-13ca712a9643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M1740_BD_PHYSICAL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M1740_BD_PHYSICAL</value>
   </webElementProperties>
</WebElementEntity>
