<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1740_3</name>
   <tag></tag>
   <elementGuidId>f3abae19-c19d-428c-ab0b-f69a100587f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#M1740_BD_VERBAL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#M1740_BD_VERBAL</value>
   </webElementProperties>
</WebElementEntity>
