<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1830_entercode</name>
   <tag></tag>
   <elementGuidId>191b9b3e-2dd1-4873-aeb8-6ec42f939a76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#code</value>
   </webElementProperties>
</WebElementEntity>
