<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1860_entercode</name>
   <tag></tag>
   <elementGuidId>0b6ffc1c-f150-4715-a588-38578519c5a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#code</value>
   </webElementProperties>
</WebElementEntity>
