<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M1870_entercode</name>
   <tag></tag>
   <elementGuidId>7d51b2cd-07f4-4cd2-9bfb-3d82097733ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#code</value>
   </webElementProperties>
</WebElementEntity>
